version: "3.9"

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8004:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

  db:
    image: postgres:13.4
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data: