version: "3.9"

services:

  web:
    build: ./project
    command: uvicorn app.main:app --workers 2 --host 0.0.0.0 --port 8004 --reload
    volumes:
      - ./project/app:/home/app/web/app
    ports:
      - "8004:8004"
    depends_on:
      - db
    env_file:
      - ./.env.dev
    restart: on-failure

  db:
    image: postgres:13.4
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data: